#!/usr/bin/env python3
"""matba (مطبع) — the press.

One tool for the whole path: posters in, book out, sealed, pushed, minted.
Local-first, stdlib only, no backend, no network except what git/gh/misty do themselves.

    python3 matba.py serve                     # web UI on http://127.0.0.1:8710
    python3 matba.py new <slug> --title "..."  # CLI mirrors every web action
    python3 matba.py intake <slug> <dir>
    python3 matba.py plates <slug>             # show / edit the plate table
    python3 matba.py build <slug>              # payload + seeder + selftest
    python3 matba.py run <slug> stage|push|mint

It does NOT reimplement git, gh or misty. It writes ONE generic seeder (the same engine that
minted zenodo.21917807, .21928710 and .21930508) and drives it. Typed gates are unchanged:
nothing pushes or mints without the operator typing the word.
"""
from __future__ import annotations
import json, os, re, shutil, subprocess, sys, threading, hashlib, html, io, time
from http.server import BaseHTTPRequestHandler, ThreadingHTTPServer
from urllib.parse import urlparse, parse_qs

VERSION = "1.0.0"
HOME = os.path.abspath(os.environ.get("MATBA_HOME", os.path.join(os.getcwd(), "matba-projects")))
TOKENS = {"stage": None, "push": "PUSH seed", "mint": None}   # mint word is per-project

# ─────────────────────────────────────────────────────────── the one generic seeder

SEEDER = r'''#!/usr/bin/env bash
# seed_%(slug)s.sh — generated by matba %(version)s. THE generic kitab seeder.
#   bash seed_%(slug)s.sh            stage only (nothing upstream)
#   bash seed_%(slug)s.sh --push     gh repo create -> seal -> push -> VERIFY -> Pages
#   bash seed_%(slug)s.sh --mint     misty ots stamp -> rehearsal -> gate -> publish -> record back
# Everything is written inside the invoking directory. gh repo create is called EXPLICITLY
# because canonical zops.sh defines _z_create_remote_if_needed and never calls it.
set -uo pipefail
VERSION="%(version)s"
SLUG="${%(ENV)s_SLUG:-%(repo)s}"
LOCAL="${%(ENV)s_LOCAL:-%(slug)s-repo}"
TEMPLATE="${%(ENV)s_TEMPLATE:-zistgah/kitab}"
TEMPLATE_DIR="${%(ENV)s_TEMPLATE_DIR:-kitab-src}"
BRANCH="${%(ENV)s_BRANCH:-main}"
VISIBILITY="${%(ENV)s_VISIBILITY:-public}"
ESTATE="${%(ENV)s_ESTATE:-/shared/estate/github}"
FORGE="${ZOPS_FORGE:-https://github.com}"
TITLE="%(title)s"
NCHAP=%(nchap)d
NFIG=%(nfig)d
MINT_WORD="MINT %(slug)s"
ZENODO_TOKEN_PATH="${ZENODO_TOKEN_PATH:-$HOME/Documents/zenodo_token_20260612}"

ROOT="$PWD"; HERE="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
STAMP="$(date -u +%%Y%%m%%dT%%H%%M%%SZ)"; LOGD="$ROOT/logs"; mkdir -p "$LOGD"
LOG="$LOGD/%(slug)s.$STAMP.log"
DO_PUSH=0; DO_MINT=0; OVERRIDE_REHEARSAL=0; DRY=0
say(){ printf '[%(slug)s] %%s\n' "$*" | tee -a "$LOG"; }
warn(){ printf '[%(slug)s] WARN  %%s\n' "$*" | tee -a "$LOG" >&2; }
die(){ printf '[%(slug)s] FATAL %%s\n' "$*" | tee -a "$LOG" >&2; exit 1; }
have(){ command -v "$1" >/dev/null 2>&1; }
run(){ if [ "$DRY" = 1 ]; then say "DRY: $*"; return 0; fi; "$@"; }
inside(){ case "$(cd "$1" 2>/dev/null && pwd)/" in "$ROOT"/*) return 0;; *) return 1;; esac; }

while [ $# -gt 0 ]; do case "$1" in
  --push) DO_PUSH=1;; --mint) DO_MINT=1;; --override-rehearsal) OVERRIDE_REHEARSAL=1;;
  --dry-run) DRY=1;; --slug) shift; SLUG="$1";;
  -h|--help) sed -n '2,8p' "$0"; exit 0;; *) die "unknown flag: $1";; esac; shift; done

resolve_src(){ local c
  for c in "$HERE" "$HERE/payload/.." "$ROOT" "$ROOT/%(slug)s"; do
    [ -f "$c/payload/book.config.json" ] && [ -d "$c/payload/posters" ] && { SRC="$(cd "$c" && pwd)"; return 0; }
  done
  local tb; for tb in "$ROOT"/%(slug)s*.tar "$ROOT"/%(slug)s*.tar.gz "$HERE"/%(slug)s*.tar; do
    [ -f "$tb" ] || continue; say "extracting $(basename "$tb")"
    tar -xf "$tb" -C "$ROOT" && { resolve_src && return 0; }
  done; die "payload not found"; }

resolve_template(){ local dest="$ROOT/$TEMPLATE_DIR"
  if [ -d "$dest/.git" ]; then say "template reuse: $TEMPLATE_DIR"
    ( cd "$dest" && git fetch -q origin 2>>"$LOG" && git reset --hard -q FETCH_HEAD 2>>"$LOG" ) || warn "template refresh failed"
  elif [ -d "$ESTATE/${TEMPLATE%%%%/*}/${TEMPLATE##*/}/.git" ]; then
    say "template from canonical estate mirror (C38)"
    run git clone -q "$ESTATE/${TEMPLATE%%%%/*}/${TEMPLATE##*/}" "$dest" || die "clone from estate failed"
  else say "cloning template $TEMPLATE"
    if have gh; then run gh repo clone "$TEMPLATE" "$dest" -- -q || die "gh repo clone $TEMPLATE failed"
    else run git clone -q "$FORGE/$TEMPLATE.git" "$dest" || die "git clone failed"; fi; fi
  [ -f "$dest/index.html" ] || die "$TEMPLATE_DIR/index.html absent — not a kitab tree"
  TPL="$dest"; say "template HEAD: $(cd "$TPL" && git rev-parse --short HEAD 2>/dev/null || echo '?')"; }

create_remote_if_needed(){ have gh || { warn "gh absent"; return 1; }
  gh repo view "$SLUG" >/dev/null 2>&1 && { say "remote exists: $SLUG"; return 0; }
  say "remote $SLUG does NOT exist upstream — creating it now, before any seal"
  [ "$DRY" = 1 ] && return 0
  local out; out="$(gh repo create "$SLUG" "--$VISIBILITY" --description "$TITLE" 2>&1)" || {
    printf '%%s\n' "$out" | tee -a "$LOG" >&2; die "gh repo create $SLUG failed"; }
  printf '%%s\n' "$out" >>"$LOG"
  gh repo view "$SLUG" >/dev/null 2>&1 || die "created $SLUG but gh repo view still fails"
  say "remote created and VERIFIED: $SLUG"; }

resolve_repo(){ local dest="$ROOT/$LOCAL"
  if [ -d "$dest/.git" ]; then
    local o; o="$(cd "$dest" && git remote get-url origin 2>/dev/null || true)"
    case "$o" in *"$SLUG"*) :;; *) die "$LOCAL exists but origin is '$o'";; esac
    say "repo reuse: $LOCAL"
  elif [ -e "$dest" ]; then die "$LOCAL exists and is not a clone"
  else
    if have gh && gh repo view "$SLUG" >/dev/null 2>&1; then say "cloning $SLUG -> $LOCAL"
      run gh repo clone "$SLUG" "$dest" -- -q || die "gh repo clone failed"
    else say "initialising $LOCAL"; run mkdir -p "$dest"
      ( cd "$dest" && run git init -q -b "$BRANCH" && run git remote add origin "$FORGE/$SLUG.git" ); fi; fi
  ( cd "$dest" && { git rev-parse --verify -q "$BRANCH" >/dev/null 2>&1 && git checkout -q "$BRANCH"; } \
      || git checkout -q -b "$BRANCH" ) 2>>"$LOG"
  REPO="$dest"; inside "$REPO" || die "$LOCAL resolved outside \$PWD"; }

overlay(){ say "overlaying kitab plumbing (never rewritten from memory) + %(slug)s data"
  local d="$REPO" p f
  for p in index.html js readers assets .nojekyll .gitignore; do
    [ -e "$TPL/$p" ] && run cp -a "$TPL/$p" "$d/" 2>>"$LOG"; done
  mkdir -p "$d/config" "$d/content" "$d/assets/figures" "$d/metadata"
  rm -f "$d"/content/*.json
  run cp -f "$SRC"/payload/content/*.json "$d/content/"
  run cp -f "$SRC"/payload/book.config.json "$d/config/book.config.json"
  for f in readers.config.json features.config.json; do
    [ -f "$TPL/config/$f" ] && run cp -f "$TPL/config/$f" "$d/config/$f"
    [ -f "$SRC/config/$f" ] && run cp -f "$SRC/config/$f" "$d/config/$f"; done
  # the template ships Lorem-Ipsum placeholders; they were minted once. assets/figures is DATA.
  rm -f "$d"/assets/figures/*.json "$d"/assets/figures/placeholder-*.svg "$d"/assets/figures/cover.svg
  run cp -f "$SRC"/payload/posters/*.png "$d/assets/figures/"
  run cp -f "$SRC"/metadata/misty.json "$d/metadata/misty.json"
  for f in CONTRACT.md CONTEXT.md README.md REVIEW.md; do
    [ -f "$SRC/overlays/$f" ] && run cp -f "$SRC/overlays/$f" "$d/$f"; done
  [ "$DRY" = 1 ] || python3 - "$d" "$SLUG" <<'PY'
import json, sys, os
d, slug = sys.argv[1], sys.argv[2]
b = os.path.join(d, "config/book.config.json")
k = json.load(open(b)); k["meta"]["repo"] = slug
json.dump(k, open(b, "w"), indent=2, ensure_ascii=False); open(b, "a").write("\n")
print("  repo -> %%s in book.config.json" %% slug)
PY
  [ -f "$d/.gitignore" ] || printf 'logs/\ndoi-package/\ndist/\n*.tar\n*.tar.gz\n' > "$d/.gitignore"
  touch "$d/.nojekyll"; }

contract(){ say "contract checks"; local bad=0
  [ -f "$REPO/index.html" ] || { warn "index.html missing at ROOT"; bad=1; }
  local n m; n=$(ls -1 "$REPO"/content/*.json 2>/dev/null | wc -l)
  m=$(ls -1 "$REPO"/assets/figures/*.png 2>/dev/null | wc -l)
  say "  chapters: $n"; say "  figures:  $m ($NCHAP chapters + cover)"
  [ "$n" = "$NCHAP" ] || { warn "expected $NCHAP chapters, found $n"; bad=1; }
  [ "$m" = "$NFIG" ]  || { warn "expected $NFIG figures, found $m"; bad=1; }
  python3 - "$REPO" "$SLUG" <<'PY' || bad=1
import json, os, sys
d, slug = sys.argv[1], sys.argv[2]; ok = True
def bad(m):
    global ok; ok = False; print("  FAIL " + m)
cfg = json.load(open(os.path.join(d, "config/book.config.json")))
if cfg["meta"]["repo"] != slug: bad("meta.repo != " + slug)
srcs = set()
for c in cfg["structure"]["chapters"]:
    p = os.path.join(d, c["source"])
    if not os.path.exists(p): bad("missing " + c["source"]); continue
    for b in json.load(open(p))["blocks"]:
        if b["type"] == "figure":
            srcs.add(os.path.basename(b["src"]))
            if not os.path.exists(os.path.join(d, b["src"])): bad("figure missing: " + b["src"])
cov = os.path.basename(cfg["meta"]["cover"])
if not os.path.exists(os.path.join(d, cfg["meta"]["cover"])): bad("cover missing")
if cov in srcs: bad("cover is also a chapter figure")
for o in set(os.listdir(os.path.join(d, "assets/figures"))) - srcs - {cov}:
    if o.endswith(".ots"): continue
    bad("undeclared file in assets/figures (it WILL be minted): " + o)
for v in ("chatgpt", "gemini", "claude", "openai", "anthropic"):
    if v in json.dumps(cfg).lower(): bad("AI vendor named in a text layer: " + v)
print("  config/content/figure triangle: " + ("OK" if ok else "FAILED"))
sys.exit(0 if ok else 1)
PY
  [ "$bad" = 0 ] || die "contract failed — nothing staged upstream"; say "contract: PASS"; }

stamp_file(){ local f="$1"; [ -f "$f" ] || return 1
  [ -f "$f.ots" ] && { say "already stamped: $(basename "$f")"; return 0; }
  [ "$DRY" = 1 ] && return 0
  if [ "${MISTY_HAS_OTS:-unknown}" = "unknown" ]; then MISTY_HAS_OTS=0
    if have misty && misty --help 2>&1 | grep -qw 'ots'; then
      misty ots --help 2>&1 | grep -qw 'stamp' && MISTY_HAS_OTS=1 || warn "misty ots advertises no stamp action"; fi; fi
  if [ "$MISTY_HAS_OTS" = 1 ]; then
    misty ots stamp "$f" >>"$LOG" 2>&1 && { say "stamped via misty ots stamp: $(basename "$f")"; return 0; }
    warn "misty ots stamp failed on $(basename "$f") — nothing fabricated"; return 1; fi
  have ots && ots stamp "$f" >>"$LOG" 2>&1 && { say "stamped via ots: $(basename "$f")"; return 0; }
  warn "no OTS client — NOTHING STAMPED, NOTHING FABRICATED"; return 1; }

seal(){ local d="$REPO" intent="$1"
  mkdir -p "$d/attest/receipts" "$d/attest/history"
  local rc="$d/attest/receipts/$STAMP-seed-%(slug)s.json"
  [ "$DRY" = 1 ] || printf '{\n  "protocol": "candor/v1",\n  "utc": "%%s",\n  "operation": "seed_%(slug)s.sh %%s",\n  "repo": "%%s",\n  "intent": "%%s",\n  "template": "%%s",\n  "template_head": "%%s",\n  "agent": "matba %(version)s"\n}\n' \
      "$STAMP" "$VERSION" "$SLUG" "$intent" "$TEMPLATE" "$(cd "$TPL" && git rev-parse HEAD 2>/dev/null || echo unknown)" > "$rc"
  stamp_file "$rc"
  if [ -f "$d/MANIFEST.sha256" ]; then
    if [ -f "$d/MANIFEST.sha256.ots" ]; then
      run mv "$d/MANIFEST.sha256" "$d/attest/history/$STAMP-MANIFEST.sha256"
      run mv "$d/MANIFEST.sha256.ots" "$d/attest/history/$STAMP-MANIFEST.sha256.ots"
    else stamp_file "$d/MANIFEST.sha256" && {
        run mv "$d/MANIFEST.sha256" "$d/attest/history/$STAMP-MANIFEST.sha256"
        run mv "$d/MANIFEST.sha256.ots" "$d/attest/history/$STAMP-MANIFEST.sha256.ots"
      } || warn "outgoing manifest has no proof — NOT archived (C5)"; fi; fi
  ( cd "$d" && git add -A >/dev/null 2>&1
    git ls-files -c -o --exclude-standard | grep -v '^MANIFEST.sha256' | sort | xargs -r sha256sum > MANIFEST.sha256.build 2>/dev/null
    mv MANIFEST.sha256.build MANIFEST.sha256 )
  stamp_file "$d/MANIFEST.sha256"
  ( cd "$d" && sha256sum -c --quiet MANIFEST.sha256 ) \
    && say "manifest VERIFIES ($(wc -l < "$d/MANIFEST.sha256") entries)" || die "manifest does not verify"; }

gate(){ local label="$1" want="$2" ans last="" i=0
  printf '\n[GATE: %%s] Type exactly  %%s  to proceed (anything else aborts):\n> ' "$label" "$want"
  # Scan up to 3 lines for an EXACT match. A stage may be skipped as idempotent, so a queued
  # answer for an un-asked gate must not be mistaken for this one. A wrong word still aborts.
  while [ $i -lt 3 ]; do
    IFS= read -r ans || { ans=""; break; }
    ans="$(printf '%%s' "$ans" | tr -d '\r' | sed 's/^ *//;s/ *$//')"
    [ "$ans" = "$want" ] && { printf '%%s\n' "$ans" >>"$LOG"; return 0; }
    [ -n "$ans" ] && last="$ans"
    i=$((i+1))
  done
  say "gate refused (got '${last:-$ans}') — nothing done"; exit 3; }

dirty(){ [ -n "$(cd "$REPO" && git status --porcelain 2>/dev/null)" ]; }

push(){ create_remote_if_needed || die "cannot proceed without a verified remote"
  if ! dirty && [ -n "$(cd "$REPO" && git rev-parse --verify -q HEAD)" ] \
     && [ "$(cd "$REPO" && git rev-parse HEAD)" = "$(git -C "$REPO" ls-remote origin "refs/heads/$BRANCH" 2>/dev/null | awk '{print $1}')" ]; then
    say "nothing changed and origin/$BRANCH already matches — push skipped (idempotent)"; pages; return 0; fi
  gate "PUSH" "PUSH seed"
  seal "seed %(slug)s: $NCHAP plates + cover"
  ( cd "$REPO" && run git add -A && run git -c user.name="${GIT_AUTHOR_NAME:-Abhishek Choudhary}" \
      -c user.email="${GIT_AUTHOR_EMAIL:-noreply@ayeai.xyz}" commit -q -m "attest: seed %(slug)s [$STAMP]" 2>>"$LOG" ) \
    || say "nothing to commit"
  local sha; sha="$(cd "$REPO" && git rev-parse HEAD)"
  run git -C "$REPO" push -u origin "$BRANCH" 2>&1 | tee -a "$LOG"
  [ "${PIPESTATUS[0]}" = 0 ] || die "push FAILED — sealed locally, NOT upstream"
  local rs; rs="$(git -C "$REPO" ls-remote origin "refs/heads/$BRANCH" 2>>"$LOG" | awk '{print $1}')"
  [ -n "$rs" ] || die "postcondition FAILED: origin/$BRANCH absent after push"
  [ "$rs" = "$sha" ] || die "postcondition FAILED: origin=$rs local=$sha"
  say "pushed and VERIFIED: $SLUG @ ${sha:0:7}"
  run git -C "$REPO" tag -a "return-to/$STAMP" -m "seed_%(slug)s $VERSION" 2>>"$LOG" || true
  run git -C "$REPO" push -q origin "return-to/$STAMP" 2>>"$LOG" || warn "return-to tag not pushed"
  pages; }

pages(){ have gh || { warn "enable Pages manually: Settings -> Pages -> $BRANCH -> /"; return; }
  gh api -X POST "repos/$SLUG/pages" -f "source[branch]=$BRANCH" -f "source[path]=/" >>"$LOG" 2>&1 \
    && say "Pages enabled: $BRANCH / (root)" || say "Pages already on (or set it in the web UI)"
  say "site:  https://$(echo "$SLUG" | cut -d/ -f1).github.io/$(echo "$SLUG" | cut -d/ -f2)/"; }

mint(){ have misty || die "misty absent — pipx install misty-doi. Nothing faked."
  [ -f "$ZENODO_TOKEN_PATH" ] || die "no Zenodo token at $ZENODO_TOKEN_PATH"
  export ZENODO_TOKEN; ZENODO_TOKEN="$(cat "$ZENODO_TOKEN_PATH")"
  [ -n "$ZENODO_TOKEN" ] || die "token file is empty"
  local help; help="$(misty publish --help 2>&1 || true)"; printf '%%s\n' "$help" >>"$LOG"
  for fl in '-m' '-f'; do printf '%%s' "$help" | grep -q -- "$fl" || die "misty publish lacks $fl — refusing to drive it blind"; done
  say "misty interface read: publish advertises -m and -f"
  local pkg="$ROOT/doi-package"; rm -rf "$pkg"; mkdir -p "$pkg"
  ( cd "$REPO" && git ls-files -c --exclude-standard ) | while IFS= read -r f; do
      mkdir -p "$pkg/$(dirname "$f")"; cp -a "$REPO/$f" "$pkg/$f"; done
  local art="$ROOT/%(slug)s-$STAMP.tar.gz"; ( cd "$pkg" && tar -czf "$art" . ) || die "packaging failed"
  say "artifact: $(basename "$art")  $(du -h "$art" | cut -f1)"; stamp_file "$art"
  local meta="$REPO/metadata/misty.json"
  misty validate -m "$meta" >>"$LOG" 2>&1 && say "metadata validates" || warn "misty validate reported findings — read $LOG"
  if [ "$OVERRIDE_REHEARSAL" = 0 ]; then
    if misty publish -m "$meta" -f "$art" --sandbox --output "$ROOT/rehearsal.json" >>"$LOG" 2>&1; then say "sandbox rehearsal PASSED"
    else warn "sandbox rehearsal did not complete (sandbox.zenodo.org needs its own token; 403 is the known dead rail)"
      warn "if the RAIL is broken rather than the artifact, rerun with --override-rehearsal"; die "stopping before the live gate"; fi
  else warn "rehearsal SKIPPED — the live gate is now the only protection"; fi
  say "MINT is the permanent step.%(review_note)s"
  gate "MINT" "$MINT_WORD"
  local res="$ROOT/mint-result.$STAMP.json"
  misty publish -m "$meta" -f "$art" --output "$res" 2>&1 | tee -a "$LOG"
  [ "${PIPESTATUS[0]}" = 0 ] || die "misty publish failed — nothing recorded"
  local doi; doi="$(python3 -c "
import json;d=json.load(open('$res'))
for k in ('doi','doi_url','conceptdoi'):
    v=d.get(k) or (d.get('metadata') or {}).get(k)
    if v: print(str(v).replace('https://doi.org/','')); break" 2>/dev/null)"
  [ -n "$doi" ] || die "misty returned no DOI — refusing to guess one"
  say "DOI minted: $doi"
  python3 - "$REPO" "$doi" <<'PY'
import json, sys, os
d, doi = sys.argv[1], sys.argv[2]
for rel, key in (("config/book.config.json", "meta"), ("metadata/misty.json", None)):
    p = os.path.join(d, rel); o = json.load(open(p))
    (o["meta"] if key else o)["doi"] = doi
    json.dump(o, open(p, "w"), indent=2, ensure_ascii=False); open(p, "a").write("\n")
print("  DOI recorded back into book.config.json and metadata/misty.json")
PY
  cp -f "$res" "$REPO/MANIFEST.misty"; seal "record DOI $doi and reseal"
  ( cd "$REPO" && run git add -A && run git -c user.name="${GIT_AUTHOR_NAME:-Abhishek Choudhary}" \
      -c user.email="${GIT_AUTHOR_EMAIL:-noreply@ayeai.xyz}" commit -q -m "attest: record DOI $doi [$STAMP]" 2>>"$LOG" ) || true
  run git -C "$REPO" push origin "$BRANCH" 2>&1 | tee -a "$LOG"
  [ "${PIPESTATUS[0]}" = 0 ] || warn "DOI recorded locally but record-back push FAILED"
  say "https://doi.org/$doi"; }

say "seed_%(slug)s.sh $VERSION   target $SLUG   template $TEMPLATE"
say "working dir: $ROOT  (nothing is written outside it)"
resolve_src; say "payload: $SRC"
resolve_template
create_remote_if_needed || warn "remote not verified yet — --push will create it before sealing"
resolve_repo; overlay; contract
( cd "$REPO" && git add -A >/dev/null 2>&1; git --no-pager diff --cached --stat | tail -4 ) | tee -a "$LOG"
if [ "$DO_PUSH" = 1 ] || [ "$DO_MINT" = 1 ]; then push; else
  say "staged only. Review $LOCAL, then: bash seed_%(slug)s.sh --push"; fi
[ "$DO_MINT" = 1 ] && mint
say "done. log: $LOG"
'''

# ─────────────────────────────────────────────────────────── model

SEED_PROMPT = ("You are reading a plate from {title}, by {author} ({affil}). This plate is "
               "\"{plate}\". Observe the Balance of Interpretation before evaluating it: interpret "
               "before judging, reconstruct before criticising, preserve the primitives before "
               "translating them into an external ontology. Reconstruct the plate on its own terms, "
               "then say where you agree, where you disagree, and what it leaves open.")


def slugify(s):
    s = re.sub(r"[^a-z0-9]+", "-", s.lower()).strip("-")
    return re.sub(r"-+", "-", s) or "untitled"


def sha256(p):
    h = hashlib.sha256()
    with open(p, "rb") as f:
        for b in iter(lambda: f.read(1 << 16), b""):
            h.update(b)
    return h.hexdigest()


def pdir(slug):
    return os.path.join(HOME, slug)


def load(slug):
    p = os.path.join(pdir(slug), "project.json")
    if not os.path.exists(p):
        raise SystemExit("no such project: %s (matba new %s)" % (slug, slug))
    return json.load(open(p))


def save(prj):
    d = pdir(prj["slug"]); os.makedirs(d, exist_ok=True)
    json.dump(prj, open(os.path.join(d, "project.json"), "w"), indent=2, ensure_ascii=False)
    return prj


def projects():
    if not os.path.isdir(HOME):
        return []
    out = []
    for s in sorted(os.listdir(HOME)):
        if os.path.exists(os.path.join(HOME, s, "project.json")):
            try: out.append(json.load(open(os.path.join(HOME, s, "project.json"))))
            except Exception: pass
    return out


def cmd_new(slug, title, subtitle="", repo=None, author="Abhishek Choudhary",
            affil="AyeAI", orcid="0009-0002-0684-8320", license="CC-BY-SA-4.0"):
    slug = slugify(slug)
    d = pdir(slug)
    for sub in ("posters", "payload/content", "payload/posters", "config", "metadata", "overlays"):
        os.makedirs(os.path.join(d, sub), exist_ok=True)
    prj = {"slug": slug, "title": title, "subtitle": subtitle,
           "repo": repo or "zistgah/" + slug, "author": author, "affiliation": affil,
           "orcid": orcid, "license": license, "template": "zistgah/kitab",
           "description": "", "keywords": [], "related": [],
           "cover": None, "parts": [], "plates": [], "created": time.strftime("%Y-%m-%dT%H:%M:%SZ")}
    save(prj)
    return prj


def cmd_intake(slug, src):
    """Copy images in, hash once, refuse duplicate bytes, keep the operator's filename."""
    prj = load(slug); d = pdir(slug)
    if not os.path.isdir(src):
        raise SystemExit("not a directory: " + src)
    seen = {p["sha256"]: p["file"] for p in prj["plates"] if p.get("sha256")}
    added, dupes = [], []
    for name in sorted(os.listdir(src)):
        if not name.lower().endswith((".png", ".jpg", ".jpeg", ".webp")):
            continue
        s = os.path.join(src, name)
        h = sha256(s)
        if h in seen:
            dupes.append((name, seen[h])); continue
        shutil.copy2(s, os.path.join(d, "posters", name))
        seen[h] = name
        prj["plates"].append({"file": name, "sha256": h, "slug": slugify(os.path.splitext(name)[0]),
                              "title": "", "subtitle": "", "lead": "", "explanation": "",
                              "topics": [], "part": "", "cover": False})
        added.append(name)
    save(prj)
    return {"added": added, "duplicates": dupes, "total": len(prj["plates"])}


def cmd_bulk(slug, tsv):
    """slug-or-filename <TAB> title <TAB> subtitle <TAB> part <TAB> topics(;) [<TAB> lead <TAB> explanation]"""
    prj = load(slug); by = {}
    for p in prj["plates"]:
        by[p["file"]] = p; by[p["slug"]] = p; by[os.path.splitext(p["file"])[0]] = p
    hit = 0
    for line in tsv.splitlines():
        if not line.strip() or line.lstrip().startswith("#"):
            continue
        col = [c.strip() for c in re.split(r"\t|\s*\|\s*", line)]
        p = by.get(col[0])
        if not p:
            continue
        hit += 1
        for i, k in enumerate(("", "title", "subtitle", "part", "topics", "lead", "explanation"), 0):
            if i == 0 or i >= len(col) or not col[i]:
                continue
            p[k] = [t.strip() for t in col[i].split(";") if t.strip()] if k == "topics" else col[i]
    save(prj)
    return hit


def cmd_set(slug, plate, **kw):
    prj = load(slug)
    for p in prj["plates"]:
        if plate in (p["file"], p["slug"], os.path.splitext(p["file"])[0]):
            if kw.get("cover"):
                for q in prj["plates"]:
                    q["cover"] = False
                prj["cover"] = p["file"]
            for k, v in kw.items():
                if v is None:
                    continue
                p[k] = [t.strip() for t in v.split(";")] if k == "topics" and isinstance(v, str) else v
            save(prj); return p
    raise SystemExit("no such plate: " + plate)


def doctor(prj):
    """Every failure here is one that actually reached a DOI once."""
    f = []
    plates = prj["plates"]
    chaps = [p for p in plates if not p.get("cover")]
    cover = [p for p in plates if p.get("cover")]
    if not plates: f.append("no plates: run intake")
    if not cover: f.append("no cover chosen (matba set <slug> <plate> --cover)")
    if len(cover) > 1: f.append("more than one cover")
    for p in chaps:
        if not p["title"]: f.append("no title: " + p["file"])
        if not p["part"]: f.append("no part: " + p["file"])
        if not p["lead"]: f.append("no lead paragraph: " + p["file"])
    slugs = [p["slug"] for p in plates]
    for s in {x for x in slugs if slugs.count(x) > 1}: f.append("duplicate slug: " + s)
    hs = [p["sha256"] for p in plates]
    for h in {x for x in hs if hs.count(x) > 1}:
        f.append("duplicate bytes: " + ", ".join(p["file"] for p in plates if p["sha256"] == h))
    blob = json.dumps(prj).lower()
    for v in ("chatgpt", "gemini", "claude", "openai", "anthropic"):
        if v in blob: f.append("AI vendor named in a text layer: " + v)
    if not prj["title"]: f.append("no book title")
    if not prj.get("description"): f.append("no description — Zenodo will show an empty abstract")
    if "/" not in prj["repo"]: f.append("repo must be owner/name")
    return f


def cmd_build(slug):
    prj = load(slug); d = pdir(slug)
    fails = doctor(prj)
    if fails:
        return {"ok": False, "doctor": fails}
    pay = os.path.join(d, "payload")
    shutil.rmtree(os.path.join(pay, "content"), ignore_errors=True)
    shutil.rmtree(os.path.join(pay, "posters"), ignore_errors=True)
    os.makedirs(os.path.join(pay, "content")); os.makedirs(os.path.join(pay, "posters"))
    chaps = [p for p in prj["plates"] if not p.get("cover")]
    cov = [p for p in prj["plates"] if p.get("cover")][0]
    shutil.copy2(os.path.join(d, "posters", cov["file"]), os.path.join(pay, "posters", "cover.png"))
    order = []
    for part in prj["parts"] or sorted({p["part"] for p in chaps}):
        pid = part["id"] if isinstance(part, dict) else slugify(part)
        ttl = part["title"] if isinstance(part, dict) else part
        members = [p for p in chaps if slugify(p["part"]) == pid or p["part"] == ttl]
        if members: order.append((pid, ttl, members))
    placed = {p["file"] for _, _, m in order for p in m}
    left = [p for p in chaps if p["file"] not in placed]
    if left: order.append(("misc", "Other", left))
    chapters, index, parts = [], [], []
    n = 0
    for pid, ttl, members in order:
        ids = []
        for p in members:
            n += 1; cid = "ch-%02d" % n
            shutil.copy2(os.path.join(d, "posters", p["file"]),
                         os.path.join(pay, "posters", p["slug"] + ".png"))
            blocks = [{"type": "paragraph", "text": p["lead"]},
                      {"type": "figure", "id": p["slug"], "dimension": "2d",
                       "src": "assets/figures/%s.png" % p["slug"], "alt": p["title"],
                       "caption": "%s — %s" % (p["title"], p["subtitle"]) if p["subtitle"] else p["title"],
                       "explanation": p["explanation"] or p["lead"], "tts": True,
                       "seed": {"enabled": True,
                                "prompt": SEED_PROMPT.format(title=prj["title"], author=prj["author"],
                                                             affil=prj["affiliation"], plate=p["title"])}}]
            if prj.get("plate_note"):
                blocks.append({"type": "callout", "variant": "note", "text": prj["plate_note"]})
            json.dump({"id": cid, "title": p["title"], "subtitle": p["subtitle"], "blocks": blocks},
                      open(os.path.join(pay, "content", cid + ".json"), "w"), indent=2, ensure_ascii=False)
            chapters.append({"id": cid, "number": n, "title": p["title"], "subtitle": p["subtitle"],
                             "source": "content/%s.json" % cid, "topics": p["topics"]})
            index.append({"chapter": cid, "slug": p["slug"], "title": p["title"],
                          "file": "posters/%s.png" % p["slug"], "sha256": p["sha256"]})
            ids.append(p["slug"])
        parts.append({"id": pid, "title": ttl, "chapters": ids})
    book = {"meta": {"title": prj["title"], "subtitle": prj["subtitle"], "author": prj["author"],
                     "affiliation": prj["affiliation"], "orcid": prj["orcid"],
                     "copyright": "Copyright (c) 1993-2026 %s. All rights reserved." % prj["author"],
                     "license": prj["license"], "doi": None, "repo": prj["repo"],
                     "cover": "assets/figures/cover.png", "language": "en"},
            "theme": {"tokens": {"--ink": "#0a0e27", "--acc": "#d4a843", "--light": "#fbf6e9"}},
            "structure": {"parts": parts, "chapters": chapters}}
    for tgt in (os.path.join(pay, "book.config.json"), os.path.join(d, "config", "book.config.json")):
        json.dump(book, open(tgt, "w"), indent=2, ensure_ascii=False); open(tgt, "a").write("\n")
    json.dump({"generator": "matba " + VERSION, "book": prj["title"],
               "cover": {"file": "posters/cover.png", "sha256": cov["sha256"]}, "figures": index},
              open(os.path.join(pay, "index.json"), "w"), indent=2, ensure_ascii=False)
    misty = {"upload_type": "publication", "publication_type": "book",
             "title": prj["title"] + (": " + prj["subtitle"] if prj["subtitle"] else ""),
             "creators": [{"name": prj["author"], "affiliation": prj["affiliation"], "orcid": prj["orcid"]}],
             "description": prj["description"], "keywords": prj["keywords"],
             "license": prj["license"].lower(), "language": "eng",
             "related_identifiers": prj["related"]}
    json.dump(misty, open(os.path.join(d, "metadata", "misty.json"), "w"), indent=2, ensure_ascii=False)
    env = re.sub(r"[^A-Z0-9]", "_", prj["slug"].upper())
    review = " See REVIEW.md." if os.path.exists(os.path.join(d, "overlays", "REVIEW.md")) else ""
    seeder = SEEDER % {"slug": prj["slug"], "repo": prj["repo"], "version": VERSION, "ENV": env,
                       "title": prj["title"].replace('"', "'"), "nchap": len(chapters),
                       "nfig": len(chapters) + 1, "review_note": review}
    sp = os.path.join(d, "seed_%s.sh" % prj["slug"])
    open(sp, "w").write(seeder); os.chmod(sp, 0o755)
    rc = subprocess.run(["bash", "-n", sp], capture_output=True, text=True)
    if rc.returncode != 0:
        return {"ok": False, "doctor": ["generated seeder does not parse: " + rc.stderr.strip()]}
    tar = os.path.join(d, "%s.tar" % prj["slug"])
    stage = os.path.join(d, "_pack", prj["slug"])
    shutil.rmtree(os.path.join(d, "_pack"), ignore_errors=True); os.makedirs(stage)
    for sub in ("payload", "config", "metadata", "overlays"):
        if os.path.isdir(os.path.join(d, sub)): shutil.copytree(os.path.join(d, sub), os.path.join(stage, sub))
    shutil.copy2(sp, stage)
    subprocess.run(["tar", "--format=ustar", "-cf", tar, prj["slug"]], cwd=os.path.join(d, "_pack"), check=True)
    shutil.rmtree(os.path.join(d, "_pack"), ignore_errors=True)
    return {"ok": True, "chapters": len(chapters), "figures": len(index) + 1, "parts": len(parts),
            "seeder": sp, "tar": tar}


def cmd_run(slug, stage, word=None, override=False, cwd=None):
    """Drive the generated seeder. Gates are answered by the typed word, never bypassed."""
    prj = load(slug); d = pdir(slug)
    sp = os.path.join(d, "seed_%s.sh" % prj["slug"])
    if not os.path.exists(sp):
        raise SystemExit("build first: matba build " + slug)
    args = ["bash", sp]
    if stage == "push": args.append("--push")
    elif stage == "mint":
        args.append("--mint")
        if override: args.append("--override-rehearsal")
    work = cwd or os.path.join(d, "work"); os.makedirs(work, exist_ok=True)
    shutil.copy2(sp, work); shutil.copy2(os.path.join(d, "%s.tar" % prj["slug"]), work)
    p = subprocess.Popen(["bash", os.path.basename(sp)] + args[2:], cwd=work,
                         stdin=subprocess.PIPE if word else None,
                         stdout=subprocess.PIPE, stderr=subprocess.STDOUT, text=True, bufsize=1)
    if word:                                   # web path: answer the gates, never bypass them
        p.stdin.write(word + "\n")            # PUSH gate
        if stage == "mint":
            p.stdin.write("MINT %s\n" % prj["slug"])
        p.stdin.close()
    return p


# ─────────────────────────────────────────────────────────── web UI

PAGE = """<!doctype html><html lang=en><head><meta charset=utf-8>
<meta name=viewport content="width=device-width,initial-scale=1"><title>matba — the press</title>
<style>
:root{--ink:#0a0e27;--acc:#d4a843;--light:#fbf6e9;--rule:rgba(212,168,67,.3);--bad:#e8a3a3;--ok:#8fca9b}
*{box-sizing:border-box}body{margin:0;background:var(--ink);color:var(--light);
font:15px/1.6 Georgia,'Times New Roman',serif}
.wrap{max-width:80rem;margin:0 auto;padding:2rem 1.25rem 5rem}
header{border-bottom:1px solid var(--rule);padding-bottom:1.25rem;margin-bottom:1.75rem;
display:flex;align-items:baseline;gap:1rem;flex-wrap:wrap}
h1{font-size:2rem;margin:0;font-weight:400;letter-spacing:-.01em}
.eyebrow{font:600 .68rem/1 ui-monospace,Menlo,monospace;letter-spacing:.22em;text-transform:uppercase;color:var(--acc)}
h2{font-size:.95rem;font-weight:400;color:var(--acc);letter-spacing:.02em;margin:2rem 0 .8rem;
padding-bottom:.4rem;border-bottom:1px solid var(--rule)}
button,input,textarea,select{font:inherit;color:inherit;background:transparent;border:1px solid var(--rule);
padding:.45rem .7rem;border-radius:0}
input,textarea,select{width:100%;background:rgba(255,255,255,.03)}
textarea{font:13px/1.5 ui-monospace,Menlo,monospace;min-height:7rem;resize:vertical}
button{cursor:pointer;background:var(--acc);color:var(--ink);border:none;
font:600 .74rem/1 ui-monospace,Menlo,monospace;letter-spacing:.09em;text-transform:uppercase;padding:.6rem 1.1rem}
button:hover{filter:brightness(1.12)}button.ghost{background:transparent;color:var(--acc);border:1px solid var(--rule)}
button:disabled{opacity:.35;cursor:not-allowed}
.row{display:grid;gap:.8rem;grid-template-columns:repeat(auto-fit,minmax(13rem,1fr))}
label{display:block;font:.72rem/1.4 ui-monospace,Menlo,monospace;letter-spacing:.06em;
text-transform:uppercase;color:rgba(251,246,233,.5);margin-bottom:.3rem}
table{width:100%;border-collapse:collapse;font-size:.88rem}
th{text-align:left;font:600 .68rem/1 ui-monospace,Menlo,monospace;letter-spacing:.1em;text-transform:uppercase;
color:var(--acc);padding:.5rem .4rem;border-bottom:1px solid var(--rule)}
td{padding:.45rem .4rem;border-bottom:1px solid rgba(212,168,67,.12);vertical-align:top}
td.mono,.mono{font-family:ui-monospace,Menlo,monospace;font-size:.8rem;color:rgba(251,246,233,.6)}
pre{background:#05070f;border:1px solid var(--rule);padding:.9rem;overflow:auto;max-height:26rem;
font:12px/1.5 ui-monospace,Menlo,monospace;white-space:pre-wrap}
.pill{display:inline-block;font:600 .62rem/1 ui-monospace,Menlo,monospace;letter-spacing:.08em;
text-transform:uppercase;padding:.3rem .5rem;border:1px solid var(--rule);color:var(--acc)}
.bad{color:var(--bad)}.ok{color:var(--ok)}
ul.d{margin:.4rem 0;padding-left:1.1rem}ul.d li{color:var(--bad);font-size:.88rem}
.bar{display:flex;gap:.6rem;flex-wrap:wrap;align-items:center;margin:.9rem 0}
.gate{border-left:2px solid var(--acc);padding-left:.9rem;margin:.9rem 0;font-size:.9rem;
color:rgba(251,246,233,.75)}
</style></head><body><div class=wrap>
<header><h1>matba</h1><span class=eyebrow id=ver></span>
<span style="flex:1"></span><select id=proj style="width:auto"></select>
<button class=ghost onclick=newProject()>New</button></header>
<div id=app></div></div>
<script>
const $=s=>document.querySelector(s);let P=null;
const api=async(p,b)=>(await fetch('/api/'+p,b?{method:'POST',headers:{'content-type':'application/json'},
  body:JSON.stringify(b)}:{})).json();
async function boot(){const r=await api('projects');$('#ver').textContent='v'+r.version+' · '+r.home;
  const sel=$('#proj');sel.innerHTML='';
  if(!r.projects.length){$('#app').innerHTML='<h2>No projects yet</h2><p>Press <b>New</b> to start one.</p>';return}
  r.projects.forEach(p=>{const o=document.createElement('option');o.value=p.slug;
    o.textContent=p.slug+' — '+p.title;sel.appendChild(o)});
  sel.onchange=()=>open_(sel.value);open_(r.projects[0].slug)}
async function newProject(){const slug=prompt('slug (repo name)');if(!slug)return;
  const title=prompt('book title');if(!title)return;
  const subtitle=prompt('subtitle (optional)')||'';
  const repo=prompt('repo owner/name','zistgah/'+slug)||'zistgah/'+slug;
  await api('new',{slug,title,subtitle,repo});boot()}
async function open_(slug){P=await api('project?slug='+encodeURIComponent(slug));render()}
function esc(s){return (s||'').replace(/[&<>"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]))}
function render(){const p=P.project,d=P.doctor;
 $('#app').innerHTML=`
 <h2>Book</h2>
 <div class=row>
  <div><label>title</label><input id=f_title value="${esc(p.title)}"></div>
  <div><label>subtitle</label><input id=f_subtitle value="${esc(p.subtitle)}"></div>
  <div><label>repo</label><input id=f_repo value="${esc(p.repo)}"></div>
  <div><label>licence</label><input id=f_license value="${esc(p.license)}"></div>
 </div>
 <div style="margin-top:.8rem"><label>description (this is the Zenodo abstract — HTML allowed)</label>
  <textarea id=f_description>${esc(p.description)}</textarea></div>
 <div class=row style="margin-top:.8rem">
  <div><label>keywords (;)</label><input id=f_keywords value="${esc((p.keywords||[]).join('; '))}"></div>
  <div><label>plate note (callout on every chapter)</label><input id=f_plate_note value="${esc(p.plate_note||'')}"></div>
 </div>
 <div class=bar><button onclick=saveMeta()>Save</button>
  <span class=mono>${p.plates.length} plates · ${HOME_HINT}</span></div>

 <h2>Plates</h2>
 <div class=bar>
  <input id=intake placeholder="folder of posters, e.g. /shared/research/20jul/plates" style="max-width:34rem">
  <button onclick=intake()>Intake</button>
  <button class=ghost onclick=bulkOpen()>Bulk paste</button>
 </div>
 <div id=bulk style="display:none"><label>file-or-slug ⇥ title ⇥ subtitle ⇥ part ⇥ topics(;) ⇥ lead ⇥ explanation</label>
  <textarea id=bulktsv></textarea><div class=bar><button onclick=bulk()>Apply</button></div></div>
 <table><thead><tr><th></th><th>file</th><th>slug</th><th>title</th><th>part</th><th>cover</th></tr></thead><tbody>
 ${p.plates.map((q,i)=>`<tr><td class=mono>${i+1}</td><td class=mono>${esc(q.file)}</td>
   <td><input value="${esc(q.slug)}" onchange="setf('${esc(q.file)}','slug',this.value)"></td>
   <td><input value="${esc(q.title)}" onchange="setf('${esc(q.file)}','title',this.value)"></td>
   <td><input value="${esc(q.part)}" onchange="setf('${esc(q.file)}','part',this.value)"></td>
   <td style="text-align:center"><input type=radio name=cov ${q.cover?'checked':''}
     onchange="setf('${esc(q.file)}','cover',true)"></td></tr>`).join('')}
 </tbody></table>

 <h2>Doctor</h2>
 ${d.length?`<ul class=d>${d.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`
   :'<p class=ok>No failures. Ready to build.</p>'}
 <div class=bar><button onclick=build() ${d.length?'disabled':''}>Build payload + seeder</button>
  <span class=mono id=buildout></span></div>

 <h2 style="cursor:pointer" onclick="document.getElementById('help').style.display=
   document.getElementById('help').style.display==='none'?'block':'none'">How-to &amp; CLI &nbsp;<span class=mono>(click)</span></h2>
 <div id=help style="display:none">
 <p class=mono style="color:rgba(251,246,233,.62)">Every button here is a CLI command. Anything you can click, you can script.</p>
 <table><thead><tr><th>step</th><th>command</th><th>what it does</th></tr></thead><tbody>
 <tr><td>1</td><td class=mono>matba new SLUG --title "..." --repo owner/name</td><td>creates the project directory</td></tr>
 <tr><td>2</td><td class=mono>matba intake SLUG /path/to/posters</td><td>copies images in, hashes once, refuses duplicate bytes</td></tr>
 <tr><td>3</td><td class=mono>matba bulk SLUG rows.tsv</td><td>fills the table: file &#8677; title &#8677; subtitle &#8677; part &#8677; topics(;) &#8677; lead &#8677; explanation</td></tr>
 <tr><td>4</td><td class=mono>matba set SLUG cover.png --cover</td><td>picks the cover (it stops being a chapter)</td></tr>
 <tr><td>5</td><td class=mono>matba doctor SLUG</td><td>exits 1 on any failure; each check is a defect that once reached a live DOI</td></tr>
 <tr><td>6</td><td class=mono>matba build SLUG</td><td>writes payload/, the generic seeder, and the tarball</td></tr>
 <tr><td>7</td><td class=mono>matba run SLUG stage</td><td>clones kitab, overlays, contract-checks. <b>Nothing upstream.</b></td></tr>
 <tr><td>8</td><td class=mono>matba run SLUG push</td><td>creates the repo if absent, seals, pushes, <b>verifies origin == local</b>, enables Pages</td></tr>
 <tr><td>9</td><td class=mono>matba run SLUG mint --override-rehearsal</td><td>OTS-stamps, mints via misty, records the DOI back, re-seals, pushes</td></tr>
 </tbody></table>
 <p style="margin-top:1rem"><b>The gates.</b> Push and mint each ask for a word typed exactly.
 A wrong word aborts with <span class=mono>rc=3</span> and records nothing. In this page you type it
 into the prompt and it is passed to the gate on stdin &mdash; never bypassed, never defaulted.</p>
 <p><b>Sandbox 403 on mint</b> is a dead rehearsal rail, not a bad artifact: sandbox.zenodo.org needs
 its own token. Tick <i>override rehearsal</i> and the live gate remains the protection.</p>
 <p><b>Environment.</b> <span class=mono>MATBA_HOME</span> holds the projects
 (currently <span class=mono id=hh></span>). Zenodo token by path via
 <span class=mono>ZENODO_TOKEN_PATH</span>, default <span class=mono>~/Documents/zenodo_token_20260612</span>
 &mdash; read from a file, never inlined. Per-book overrides: <span class=mono>&lt;SLUG&gt;_SLUG</span>,
 <span class=mono>_TEMPLATE</span>, <span class=mono>_ESTATE</span>, <span class=mono>_BRANCH</span>,
 <span class=mono>_VISIBILITY</span>.</p>
 <p><b>What it does not do.</b> It never reimplements git, gh or misty. It writes one generic seeder
 &mdash; the same engine behind zenodo.21917807, .21928710 and .21930508 &mdash; and drives it.</p>
 </div>

 <h2>Run</h2>
 <div class=gate>Gates are unchanged. <b>Stage</b> writes nothing upstream.
  <b>Push</b> creates the repo if absent, seals, pushes and verifies.
  <b>Mint</b> is permanent — you type the word here and it is passed to the gate, never bypassed.</div>
 <div class=bar>
  <button class=ghost onclick="run_('stage')">Stage</button>
  <button onclick="run_('push')">Push</button>
  <button onclick="run_('mint')">Mint</button>
  <label style="display:flex;align-items:center;gap:.4rem;margin:0;text-transform:none">
   <input type=checkbox id=ovr style="width:auto"> override rehearsal</label>
 </div>
 <pre id=log>—</pre>`;
 window.HOME_HINT=P.dir;const h=document.getElementById('hh');if(h)h.textContent=P.home||P.dir}
async function saveMeta(){const g=id=>$('#f_'+id).value;
 await api('save',{slug:P.project.slug,title:g('title'),subtitle:g('subtitle'),repo:g('repo'),
  license:g('license'),description:g('description'),plate_note:g('plate_note'),
  keywords:g('keywords').split(';').map(s=>s.trim()).filter(Boolean)});open_(P.project.slug)}
async function setf(file,k,v){await api('setplate',{slug:P.project.slug,file,key:k,value:v});open_(P.project.slug)}
async function intake(){const r=await api('intake',{slug:P.project.slug,dir:$('#intake').value});
 if(r.error)alert(r.error);else if(r.duplicates.length)alert('skipped duplicate bytes:\\n'+
  r.duplicates.map(d=>d[0]+' == '+d[1]).join('\\n'));open_(P.project.slug)}
function bulkOpen(){const b=$('#bulk');b.style.display=b.style.display==='none'?'block':'none'}
async function bulk(){const r=await api('bulk',{slug:P.project.slug,tsv:$('#bulktsv').value});
 alert(r.matched+' rows matched');open_(P.project.slug)}
async function build(){$('#buildout').textContent='building…';const r=await api('build',{slug:P.project.slug});
 $('#buildout').textContent=r.ok?`${r.chapters} chapters · ${r.figures} figures · ${r.parts} parts → ${r.tar}`
  :'FAILED';if(!r.ok)alert(r.doctor.join('\\n'));open_(P.project.slug)}
async function run_(stage){
 let word=null;
 if(stage!=='stage'){word=prompt('Type the PUSH gate word exactly:','PUSH seed');if(word===null)return}
 if(stage==='mint'&&!confirm('MINT is permanent. The mint gate word will be sent too. Continue?'))return;
 const r=await api('run',{slug:P.project.slug,stage,word,override:$('#ovr').checked});
 if(r.error){alert(r.error);return}
 const t=setInterval(async()=>{const s=await api('log?slug='+P.project.slug);
  const el=$('#log');el.textContent=s.log||'—';el.scrollTop=el.scrollHeight;
  if(!s.running){clearInterval(t);open_(P.project.slug)}},900)}
boot();
</script></body></html>"""


class Handler(BaseHTTPRequestHandler):
    runs = {}

    def _send(self, obj, code=200, ctype="application/json"):
        body = obj if isinstance(obj, bytes) else (obj if isinstance(obj, str) else json.dumps(obj)).encode()
        self.send_response(code); self.send_header("Content-Type", ctype)
        self.send_header("Content-Length", str(len(body))); self.end_headers(); self.wfile.write(body)

    def log_message(self, *a):
        pass

    def do_GET(self):
        u = urlparse(self.path); q = parse_qs(u.query)
        if u.path in ("/", "/index.html"):
            return self._send(PAGE, ctype="text/html; charset=utf-8")
        if u.path == "/api/projects":
            return self._send({"version": VERSION, "home": HOME, "projects": projects()})
        if u.path == "/api/project":
            prj = load(q["slug"][0])
            return self._send({"project": prj, "doctor": doctor(prj), "dir": pdir(prj["slug"]), "home": HOME})
        if u.path == "/api/log":
            s = q["slug"][0]; r = self.runs.get(s)
            if not r: return self._send({"log": "", "running": False})
            return self._send({"log": r["buf"].getvalue(), "running": r["proc"].poll() is None})
        return self._send({"error": "not found"}, 404)

    def do_POST(self):
        u = urlparse(self.path)
        n = int(self.headers.get("Content-Length") or 0)
        b = json.loads(self.rfile.read(n) or "{}")
        try:
            if u.path == "/api/new":
                return self._send(cmd_new(b["slug"], b["title"], b.get("subtitle", ""), b.get("repo")))
            if u.path == "/api/save":
                prj = load(b["slug"])
                for k in ("title", "subtitle", "repo", "license", "description", "keywords", "plate_note"):
                    if k in b: prj[k] = b[k]
                return self._send(save(prj))
            if u.path == "/api/intake":
                return self._send(cmd_intake(b["slug"], b["dir"]))
            if u.path == "/api/bulk":
                return self._send({"matched": cmd_bulk(b["slug"], b["tsv"])})
            if u.path == "/api/setplate":
                return self._send(cmd_set(b["slug"], b["file"], **{b["key"]: b["value"]}))
            if u.path == "/api/build":
                return self._send(cmd_build(b["slug"]))
            if u.path == "/api/run":
                s = b["slug"]
                old = self.runs.get(s)
                if old and old["proc"].poll() is None:
                    return self._send({"error": "already running"}, 409)
                p = cmd_run(s, b["stage"], b.get("word"), b.get("override"))
                buf = io.StringIO(); self.runs[s] = {"proc": p, "buf": buf}
                threading.Thread(target=lambda: [buf.write(l) for l in p.stdout], daemon=True).start()
                return self._send({"started": True})
        except SystemExit as e:
            return self._send({"error": str(e)}, 400)
        except Exception as e:
            return self._send({"error": "%s: %s" % (type(e).__name__, e)}, 500)
        return self._send({"error": "not found"}, 404)


def serve(port=8710):
    os.makedirs(HOME, exist_ok=True)
    srv = ThreadingHTTPServer(("127.0.0.1", port), Handler)
    print("matba %s — http://127.0.0.1:%d   projects: %s" % (VERSION, port, HOME))
    print("Ctrl-C to stop. Nothing pushes or mints without you typing the gate word.")
    try: srv.serve_forever()
    except KeyboardInterrupt: print("\nstopped.")


def main(argv):
    if len(argv) < 2:
        print(__doc__); return 0
    c = argv[1]
    if c == "serve":
        return serve(int(argv[2]) if len(argv) > 2 else 8710)
    if c == "new":
        t = argv[argv.index("--title") + 1] if "--title" in argv else argv[2]
        s = argv[argv.index("--subtitle") + 1] if "--subtitle" in argv else ""
        r = argv[argv.index("--repo") + 1] if "--repo" in argv else None
        print(json.dumps(cmd_new(argv[2], t, s, r), indent=2)); return 0
    if c == "intake":
        print(json.dumps(cmd_intake(argv[2], argv[3]), indent=2)); return 0
    if c == "bulk":
        tsv = open(argv[3]).read() if len(argv) > 3 else sys.stdin.read()
        print("%d rows matched" % cmd_bulk(argv[2], tsv)); return 0
    if c == "plates":
        for i, p in enumerate(load(argv[2])["plates"], 1):
            print("%2d  %-34s %-28s %-18s %s" % (i, p["file"], p["slug"], p["part"],
                                                 "COVER" if p.get("cover") else p["title"][:40]))
        return 0
    if c == "set":
        kw = {}
        for k in ("slug", "title", "subtitle", "part", "topics", "lead", "explanation"):
            if "--" + k in argv: kw[k] = argv[argv.index("--" + k) + 1]
        if "--cover" in argv: kw["cover"] = True
        print(json.dumps(cmd_set(argv[2], argv[3], **kw), indent=2)); return 0
    if c == "doctor":
        f = doctor(load(argv[2]))
        print("\n".join("FAIL " + x for x in f) if f else "no failures"); return 1 if f else 0
    if c == "build":
        r = cmd_build(argv[2]); print(json.dumps(r, indent=2)); return 0 if r["ok"] else 1
    if c == "run":
        p = cmd_run(argv[2], argv[3], override="--override-rehearsal" in argv)
        for line in p.stdout: sys.stdout.write(line)
        return p.wait()
    print("unknown command: " + c); return 2


if __name__ == "__main__":
    try:
        rc = main(sys.argv)
    except BrokenPipeError:                     # `matba build | grep -q ...` closes the pipe early
        try: sys.stdout.close()
        except Exception: pass
        os._exit(0)
    except KeyboardInterrupt:
        print(); rc = 130
    try:
        sys.stdout.flush()
    except BrokenPipeError:
        os._exit(rc or 0)
    sys.exit(rc)
